### PR TITLE
Fixes for PR comments

### PR DESCRIPTION
**Pull request by nosmirck**
- Removed unnecessary changes on gradle files
- Added validations for resizeQuality property.
- Fixed a few formatting errors on the code

### CODE REVIEW

**Comment by nosmirck** [comment]
Once you merge this, the PR in the flutter/plugins will have the unnecessary changes reverted back plus the few fixes and validations I added.

**Comment by katout** [comment]
I'm happy that you could create pr!

but, You probably need to read https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md.
https://github.com/flutter/flutter/issues/12864

**Comment by nosmirck** [comment]
Done, I accepted the contributors license agreement. I'm ok if I'm not in the authors file, it's your contribution, I just enhanced it a bit because I need this feature (I was already using my own branch, saw yours was identical to mine and decided to simply add the changes to yours) . You can now merge this and let's hope they accept it soon so everyone else can have this needed feature.

**Comment by katout** [comment]
I downloaded your pr and confirmed it,  but there was a problem with format.
you need [pub global run flutter_plugin_tools format --plugins image_picker]

**Comment by nosmirck** [comment]
> I downloaded your pr and confirmed it, but there was a problem with format.
> you need [pub global run flutter_plugin_tools format --plugins image_picker]

I tried what you mentioned and it gives me this error on my branch:
```
Formatting all .dart files...
Unchanged /home/luis/Repos/plugins/packages/image_picker/lib/image_picker.dart
Unchanged /home/luis/Repos/plugins/packages/image_picker/example/lib/main.dart
Unchanged /home/luis/Repos/plugins/packages/image_picker/test/image_picker_test.dart
Formatting all .java files...
Unhandled exception:
ProcessException: No such file or directory
  Command: java -jar /home/luis/.pub-cache/global_packages/flutter_plugin_tools/bin/google-java-format-1.3-all-deps.jar --replace /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/main/java/io/flutter/plugins/imagepickerexample/MainActivity.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerFileProvider.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ExifDataCopier.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:193:7)
<asynchronous suspension>
#1      FormatCommand._formatJava (package:flutter_plugin_tools/src/format_command.dart:90:11)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:40:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:109:11)
#7      main (package:flutter_plugin_tools/src/main.dart:41:17)
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
And if I do the same on the master branch:
```
Formatting all .dart files...
Unchanged /home/luis/Repos/plugins/packages/image_picker/lib/image_picker.dart
Unchanged /home/luis/Repos/plugins/packages/image_picker/example/lib/main.dart
Unchanged /home/luis/Repos/plugins/packages/image_picker/test/image_picker_test.dart
Formatting all .java files...
Unhandled exception:
ProcessException: No such file or directory
  Command: java -jar /home/luis/.pub-cache/global_packages/flutter_plugin_tools/bin/google-java-format-1.3-all-deps.jar --replace /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/main/java/io/flutter/plugins/imagepickerexample/MainActivity.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerFileProvider.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ExifDataCopier.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:193:7)
<asynchronous suspension>
#1      FormatCommand._formatJava (package:flutter_plugin_tools/src/format_command.dart:90:11)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:40:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:109:11)
#7      main (package:flutter_plugin_tools/src/main.dart:41:17)
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Same error...

On your branch:
```
Formatting all .dart files...
Unchanged /home/luis/Repos/plugins/packages/image_picker/lib/image_picker.dart
Unchanged /home/luis/Repos/plugins/packages/image_picker/example/lib/main.dart
Unchanged /home/luis/Repos/plugins/packages/image_picker/test/image_picker_test.dart
Formatting all .java files...
Unhandled exception:
ProcessException: No such file or directory
  Command: java -jar /home/luis/.pub-cache/global_packages/flutter_plugin_tools/bin/google-java-format-1.3-all-deps.jar --replace /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/main/java/io/flutter/plugins/imagepickerexample/MainActivity.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java /home/luis/Repos/plugins/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerFileProvider.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ExifDataCopier.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java /home/luis/Repos/plugins/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:193:7)
<asynchronous suspension>
#1      FormatCommand._formatJava (package:flutter_plugin_tools/src/format_command.dart:90:11)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:40:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:109:11)
#7      main (package:flutter_plugin_tools/src/main.dart:41:17)
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Same error.

So, I'm pretty sure the error is with the flutter_plugin_tools.

if I run flutter format, no changes are needed.

**Comment by katout** [comment]
nice!
sorry I forgot, you can see the history of my pr, but if you do not set the gradle the google test will not succeed.

**Comment by nosmirck** [comment]
Oh, should I set it here too?

**Comment by katout** [comment]
I think Revert this files.
packages/image_picker/android/build.gradle
packages/image_picker/example/android/build.gradle
packages/image_picker/example/android/gradle/wrapper/gradle-wrapper.properties

**Comment by nosmirck** [comment]
Wait... Didn't we agree that those files had unnecessary changes? It was the main reason I reverted them back to the same as current master branch in flutter/plugins.

The feature I to add a resizeQuality parameter, right? Not to upgrade gradle versions.

It changed for you because you probably used Android Studio and automatically upgraded those, but it's not needed, the flutter plugins team are the ones responsible for those changes when needed.

I believe we shouldn't touch that and only mes with relevant code to the feature/fix we add.

**Comment by katout** [comment]
Ok.
I've created pr for flutter/plugin to update gradle settings.

**Pull request closed without merging**
